# Generated by Django 4.2 on 2023-04-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='is_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
